<div class="bs-docs-section"
<div class ="well">
    <?php
    $form->setAttribute('action', $this->url('admin/article', ['action' => 'edit', 'id' => $id]));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo '<fieldset><legend>Редактирование статьи</legend>';
    foreach ($form as $element) {
        echo '<div class="form-group">';
        $attributes = $element->getAttributes();

        if($element->getLabel()){
            $element->setLabelAttributes(['class' =>'col-lg-2 control-label']);
            if(isset($attributes['required'])){
                $element->setLabel($element->getLabel() . ' *');
            }
        }

        if(isset($attributes['type']) && $attributes['type'] == 'text')
        {
            echo $this->formLabel($element);
            echo '<div class="col-lg-10">';
            echo $this->formInput($element);
            echo '</div>';
        }
        elseif(isset($attributes['type']) && $attributes['type'] == 'textarea')
        {
            echo $this->formLabel($element);
            echo '<div class="col-lg-10">';
            echo $this->formTextArea($element);
            echo '</div>';
        }
        elseif(isset($attributes['type']) && $attributes['type'] == 'select')
        {
            echo $this->formLabel($element);
            echo '<div class="col-lg-10">';
            echo $this->formSelect($element);
            echo '</div>';
        }
        else
        {
            echo '<div class="col-lg-10">';
            echo $this->formRow($element);
            echo '</div>';
        }
        echo '</div>';
    }
    echo '</fieldset>';
    echo $this->form()->closeTag();
    ?>
</div>

