<div class="bs-docs-section"
<div class ="well">
    <?php
    $form->setAttribute('action', $this->url('admin/article', ['action' => 'add']));
    $form->prepare();

    echo $this->form()->openTag($form);
    echo '<fieldset><legend>Добавление статьи</legend>';
    foreach ($form as $element) {
        echo '<div class="form-group">';
        $attributes = $element->getAttributes();
        $label = '';
        if($element->getLabel()){
            $element->setLabelAttributes(['class' =>'col-lg-2 control-label']);
            $label = $element->getLabel();
            if(isset($attributes['required'])){
                $label .= '&nbsp;*';
            }
        }

        $type = isset($attributes['type']) ? $attributes['type'] : '';
        $formElement = '';
        switch ($type) {
            case 'text':
                $formElement = $this->formInput($element);
                break;

            case 'textarea':
                $formElement = $this->formTextArea($element);
                break;

            case 'select':
                $formElement= $this->formSelect($element);
                break;

            default:
                $formElement = $this->formRow($element);
                $label = '';
                break;
        }
        echo "{$label}<div class='col-lg-10'>{$formElement}</div>";
        echo '</div>';
    }
    echo '</fieldset>';
    echo $this->form()->closeTag();
    ?>
</div>

<script src="/js/ckeditor/ckeditor.js"></script>