<h1>Статьи</h1>
<a href="/admin/article/add">Добавить</a><br><br>
<?php
    $flash = $this->flashMessenger();
    $flash->setMessageOpenFormat('<div%s>
        <button type="button" class="close" data-dismiss="alert" area-hidden="true">
        &times;
        </button>
        <ul><li>')
        ->setMessageSeparatorString('</li><li>')
        ->setMessageCloseString('</li></ul></div>');

    echo $flash->render('error', ['alert', 'alert-dismissable', 'alert-danger']);
    echo $flash->render('info', ['alert', 'alert-dismissable', 'alert-danger']);
    echo $flash->render('default', ['alert', 'alert-dismissable', 'alert-danger']);
    echo $flash->render('success', ['alert', 'alert-dismissable', 'alert-danger']);
    ?>

<table class="table table-striped table-hover">
    <tbody><tr>
        <th>#</th>
        <th>Категория</th>
        <th>Заголовок</th>
        <th>Статья</th>
        <th>Начало статьи</th>
        <th>Опубликовано</th>
        <th>Действие</th>
    </tr>

<?php

foreach ($articles as $item) {
    $category = $item->getCategory();
    if ($category) {
        $catName = $category->getCategoryName();
    } else {
        $catName = '';
    }
    if ($item->getIsPublic()) {
        $isPublic = 'Да';

    } else {
        $isPublic = 'Нет';
    }
    echo "<tr>
    <td>{$item->getId()}</td>
    <td>{$catName}</td>
    <td>{$item->getTitle()}</td>
    <td>{$item->getArticleForTable()}</td>
    <td>{$item->getShortArticleForTable()}</td>
    <td>{$isPublic}</td>";

    echo '<td><a href="' . $this->url('admin/article', ['action' => 'edit', 'id' => $item->getId()]) . '">Редактировать</a> &nbsp;&nbsp;
        <a href="' . $this->url('admin/article', ['action' => 'delete', 'id' => $item->getId()]) . '" onlclick="if (confirm(\'Удалить запись?\')) {document.location = this.href;} return false; ">Удалить</a> </td>';
}
?>
</tbody></table>

<?php

echo $this->paginationControl($articles,'sliding','pagination_control', ['route' => 'admin/article']);