<?php

$form = $this->form;
$form->get('order')->setAttributes([
    'class'=>'order',
]);
$form->prepare();

?>



<div class="container">
    <div class="check">
        <h1>My Shopping Bag (<?= $this->escapeHtml(count($carts)); ?>)</h1>
        <div class="col-md-9 cart-items">
            <?php $prodcount = null ?>
            <?php foreach ($carts as $token=>$cart): ?>
                <?php $prodcount ++ ?>
            <script>$(document).ready(function(c) {
                    $('.close<?= $this->escapeHtml($prodcount); ?>').on('click', function(c){
                        $('.cart-header<?= $this->escapeHtml($prodcount); ?>').fadeOut('slow', function(c){
                            $('.cart-header<?= $this->escapeHtml($prodcount); ?>').remove();
                        });
                    });
                });
            </script>
            <div class="cart-header<?= $this->escapeHtml($prodcount); ?>">
                <div class="close<?= $this->escapeHtml($prodcount); ?>"> </div>
                <div class="cart-sec simpleCart_shelfItem">
                    <div class="cart-item cyc">
                        <img src="<?= $this->escapeHtml($cart->getLogo()); ?>" class="img-responsive" alt=""/>
                    </div>
                    <div class="cart-item-info">
                        <h3><a href="#"><?= $this->escapeHtml($cart->getProduct()); ?></a><span>Model No: 3578</span></h3>
                        <ul class="qty">
                            <li><p>Size : 5</p></li>
                            <li><p>Qty : <?= $this->escapeHtml($cart->getQty()); ?></p></li>
                        </ul>

                        <div class="delivery">
                            <p>Service Charges : Rs.100.00</p>
                            <span>Delivered in 2-3 bussiness days</span>
                            <div class="clearfix"></div>
                        </div>
                    </div>
                    <div class="clearfix"></div>

                </div>
            </div>
            <?php endforeach; ?>
        </div>
        <div class="col-md-3 cart-total">
            <a class="continue" href="#">Continue to basket</a>
            <div class="price-details">
                <h3>Price Details</h3>
                <span>Total</span>
                <span class="total1"><?= $this->escapeHtml($totalcost); ?></span>
                <span>Discount</span>
                <span class="total1">---</span>
                <span>Delivery Charges</span>
                <span class="total1">150.00</span>
                <div class="clearfix"></div>
            </div>
            <ul class="total_price">
                <li class="last_price"> <h4>TOTAL</h4></li>
                <li class="last_price"><span><?= $this->escapeHtml($totalcost); ?></span></li>
                <div class="clearfix"> </div>
            </ul>


            <div class="clearfix"></div>
            <?= $this->form()->openTag($form); ?>
            <?= $this->formElement($form->get('order')); ?>
            <?= $this->form()->closeTag(); ?>
            <div class="total-item">
                <h3>OPTIONS</h3>
                <h4>COUPONS</h4>
                <a class="cpns" href="#">Apply Coupons</a>
                <p><a href="#">Log In</a> to use accounts - linked coupons</p>
            </div>
        </div>

        <div class="clearfix"> </div>
    </div>
</div>
