<table class="table table-striped">
<?php $form = $this->form ?>
    <tr>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Quantity</th>
        <th>Price</th>
    </tr>

    <?php foreach ($carts as $token=>$cart): ?>
        <tr>
            <td><?= $this->escapeHtml($cart->getProduct()); ?></td>
            <td><?= $this->escapeHtml($cart->getStart()); ?></td>
            <td><?= $this->escapeHtml($cart->getEnd()); ?></td>
            <td><?= $this->escapeHtml($cart->getQty()); ?></td>
            <td><?= $this->escapeHtml($cart->getPrice()); ?></td>
        </tr>
    <?php endforeach; ?>

</table>
<?= $this->form()->openTag($form); ?>
<?= $this->formElement($form->get('order')); ?>
<?= $this->form()->closeTag(); ?>