<?php

$form = $this->form;
$form->get('category')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Choose category here'
]);
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter subcategory name here'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>

<h1>Add new subcategory</h1>

<p>
    Enter new subcategory name,choose category and click on the button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('category')); ?>
            <?= $this->formElement($form->get('category')); ?>
            <?= $this->formElementErrors($form->get('category')); ?>
        </div>

        <div class="form-group">
        <?= $this->formLabel($form->get('name')); ?>
        <?= $this->formElement($form->get('name')); ?>
        <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>