<!-- /.row -->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Manage Categories</h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>ID</th>
                        <th>Category name</th>
                        <th>Actions</th>
                    </tr>
                    <?php foreach ($categories as $category): ?>
                        <tr>
                            <td><?= $this->escapeHtml($category->getId()); ?></td>
                            <td><?= $this->escapeHtml($category->getName()); ?></td>
                            <td>
                                <a class="btn btn-info" href="<?= $this->url('admin',
                                    ['action'=>'edit-category', 'id'=>$category->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                                </a>
                                <a class="btn btn-danger" href="<?= $this->url('admin',
                                    ['action'=>'delete-category', 'id'=>$category->getId()]); ?>">
                                    <span class="glyphicon glyphicon-remove"></span> Delete
                                </a>
                            </td>
                        </tr>
                    <?php endforeach; ?>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>