<?php
$this->headTitle('Edit User');
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'name@example.com'
]);
$form->get('first_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'John'
]);
$form->get('last_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Doe'
]);
$form->get('status')->setAttributes([
    'class'=>'form-control'
]);
$form->get('gender')->setAttributes([
    'class'=>'form-control'
]);
$form->get('submit')
    ->setAttributes(['class'=>'btn btn-primary'])
    ->setValue('Save');
$form->prepare();
?>

<h1>Edit User <?= $this->escapeHtml($user->getEmail()) ?></h1>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('first_name')); ?>
            <?= $this->formElement($form->get('first_name')); ?>
            <?= $this->formElementErrors($form->get('first_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('last_name')); ?>
            <?= $this->formElement($form->get('last_name')); ?>
            <?= $this->formElementErrors($form->get('last_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('gender')); ?>
            <?= $this->formElement($form->get('gender')); ?>
            <?= $this->formElementErrors($form->get('gender')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>