<!-- /.row -->
<div class="row">
    <div class="col-xs-12">
        <div class="box">
            <div class="box-header">
                <h3 class="box-title">Manage Categories</h3>

                <div class="box-tools">
                    <div class="input-group input-group-sm" style="width: 150px;">
                        <input type="text" name="table_search" class="form-control pull-right" placeholder="Search">

                        <div class="input-group-btn">
                            <button type="submit" class="btn btn-default"><i class="fa fa-search"></i></button>
                        </div>
                    </div>
                </div>
            </div>
            <!-- /.box-header -->
            <div class="box-body table-responsive no-padding">
                <table class="table table-hover">
                    <tr>
                        <th>ID</th>
                        <th>E-mail</th>
                        <th>Full Name</th>
                        <th>Status</th>
                        <th>Gender</th>
                        <th>Actions</th>
                    </tr>

                    <?php foreach ($users as $user): ?>

                        <tr>
                            <td><?= $this->escapeHtml($user->getId()); ?></td>
                            <td>
                                <a href="<?= $this->url('admin', ['action'=>'view-user', 'id'=>$user->getId()]); ?>">
                                    <?= $this->escapeHtml($user->getEmail()); ?>
                                </a>
                            </td>
                            <td><?= $this->escapeHtml($user->getFullName()); ?></a>
                            </td>
                            <td><?= $this->escapeHtml($user->getStatusAsString()); ?></td>
                            <td><?= $this->escapeHtml($user->getGenderAsString()); ?></td>
                            <td>
                                <a class="btn btn-info" href="<?= $this->url('admin',
                                    ['action'=>'edit-user', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                                </a>
                                <a class="btn btn-default" href="<?= $this->url('admin',
                                    ['action'=>'change-password', 'id'=>$user->getId()]); ?>">
                                    <span class="glyphicon glyphicon-asterisk"></span> Change Password
                                </a>
                            </td>
                        </tr>

                    <?php endforeach; ?>
                </table>
            </div>
            <!-- /.box-body -->
        </div>
        <!-- /.box -->
    </div>
</div>