<?php

$form = $this->form;
$form->get('category')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Choose scategory here'
]);
$form->get('name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter product name here'
]);
$form->get('price')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter price here'
]);
$form->get('description')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter description here'
]);
$form->get('quantity')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter quantity here'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->prepare();

?>

<h1>Add new product</h1>

<p>
    Enter new product details and click on the button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('category')); ?>
            <?= $this->formElement($form->get('category')); ?>
            <?= $this->formElementErrors($form->get('category')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('name')); ?>
            <?= $this->formElement($form->get('name')); ?>
            <?= $this->formElementErrors($form->get('name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('description')); ?>
            <?= $this->formElement($form->get('description')); ?>
            <?= $this->formElementErrors($form->get('description')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('quantity')); ?>
            <?= $this->formElement($form->get('quantity')); ?>
            <?= $this->formElementErrors($form->get('quantity')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('price')); ?>
            <?= $this->formElement($form->get('price')); ?>
            <?= $this->formElementErrors($form->get('price')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>