<?php

$form = $this->form;
$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter username here'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Save');
$form->prepare();

?>

<h1>Edit order</h1>

<p>
    Enter order name and click on the button.
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('email')); ?>
            <?= $this->formElement($form->get('email')); ?>
            <?= $this->formElementErrors($form->get('email')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('costs')); ?>
            <?= $this->formElement($form->get('costs')); ?>
            <?= $this->formElementErrors($form->get('costs')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('status')); ?>
            <?= $this->formElement($form->get('status')); ?>
            <?= $this->formElementErrors($form->get('status')); ?>
        </div>

        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>