<h1>Manage Images</h1>


<p>
    <a class="btn btn-default" href="
        <?= $this->url('admin', ['action'=>'add-product-images', 'id' => $prodid])?>">
        New Image
    </a>
</p>

<table class="table table-striped">

    <tr>
        <th>ID</th>
        <th>Link</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($images as $image): ?>
        <tr>
            <td><?= $this->escapeHtml($image->getId()); ?></td>
            <td><?= $this->escapeHtml($image->getLink()); ?></td>
            <td>
                <a class="btn btn-info" href="<?= $this->url('admin',
                    ['action'=>'edit-prodimg', 'id'=>$image->getId()]); ?>">
                    <span class="glyphicon glyphicon-pencil" ></span> Edit
                </a>
                <a class="btn btn-danger" href="<?= $this->url('admin',
                    ['action'=>'remove-prodimg', 'id'=>$image->getId()]); ?>">
                    <span class="glyphicon glyphicon-remove"></span> Delete
                </a>
            </td>
        </tr>
    <?php endforeach; ?>
</table>