<link href="/css/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css" media="all" />
<script src="/js/moment.js"> </script>
<script src="/js/bootstrap-datetimepicker.min.js"> </script>
<script src="/js/ru.js"> </script>
<?php
$this->headTitle('Products');


$form->get('start')->setAttributes([

    'placeholder'=>'Starting date',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('end')->setAttributes([
    'placeholder'=>'Ending date',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>




<!--content-->
<!---->
<div class="product">
    <div class="container">
        <div class="col-md-3 product-price">

            <div class=" rsidebar span_1_of_left">
                <div class="of-left">
                    <h3 class="cate">Categories</h3>
                </div>
                <ul class="menu">
                    <?php $itemcount = null; foreach($categories as $category): $itemcount++; ?>
                        <li class="item<?= $itemcount ?>"><a href="<?= $this->url('shop/category',['id' => $itemcount]); ?>"><?= ucfirst($category->getName()) ?></a>
                            <ul class="cute">
                                <?php $subcount = null; foreach(($this->categoriesHelper()->findSubcategories($category)) as $subcategory): $subcount++;?>
                                    <li class="subitem<?= $subcount ?>"><a href="<?= $this->url('shop/category/subcategory',['id'=>$category->getId(),'subid' => $subcategory->getId()]);?>"><?= ucfirst($subcategory->getName()) ?> </a></li>
                                <?php endforeach; ?>
                            </ul>
                        </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <!--initiate accordion-->
            <script type="text/javascript">
                $(function() {
                    var menu_ul = $('.menu > li > ul'),
                        menu_a  = $('.menu > li > a');
                    menu_ul.hide();
                    menu_a.click(function(e) {
                        e.preventDefault();
                        if(!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true,true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true,true).slideUp('normal');
                        }
                    });

                });
            </script>
            <!---->
            <div class="product-middle">


            </div>
            <div class="sellers">
                <div class="of-left-in">
                    <h3 class="tag">Tags</h3>
                </div>
                <div class="tags">
                    <ul>
                        <li><a href="#">bicycles</a></li>
                        <li><a href="#">shop</a></li>
                        <li><a href="#">rent</a></li>
                        <li><a href="#">road</a></li>
                        <li><a href="#">bmx</a></li>
                        <li><a href="#">mountain</a></li>
                        <li><a href="#">men's</a></li>
                        <li><a href="#">women's</a></li>
                        <li><a href="#">rent</a></li>
                        <li><a href="#">store</a></li>
                        <li><a href="#">hybrid</a></li>
                        <li><a href="#">cruiser</a></li>

                        <div class="clearfix"> </div>
                    </ul>

                </div>

            </div>
            <!---->

            <div class=" per1">
                <a href="#" ><img class="img-responsive" src="/img/pro.jpg" alt="">
                    <div class="six1">
                        <h4>DISCOUNT</h4>
                    </div></a>
            </div>
        </div>
        <div class="col-md-9 product-price1">
            <div class="col-md-5 single-top">
                <div class="flexslider">
                    <ul class="slides">
                        <?php foreach ($images as $image) : ?>
                        <li data-thumb="/<?= $image->getLink() ?>">
                            <img src="/<?= $image->getLink() ?>" />
                        </li>
                        <?php endforeach; ?>
                    </ul>
                </div>
                <!-- FlexSlider -->
                <script defer src="/js/jquery.flexslider.js"></script>
                <link rel="stylesheet" href="/css/flexslider.css" type="text/css" media="screen" />

                <script>
                    // Can also be used with $(document).ready()
                    $(document).ready(function() {
                        $('.flexslider').flexslider({
                            animation: "slide",
                            controlNav: "thumbnails"
                        });
                    });
                </script>
            </div>
            <div class="col-md-7 single-top-in simpleCart_shelfItem">
                <div class="single-para ">
                    <h4><?= $product->getName() ?></h4>
                    <div class="star-on">
                        <ul class="star-footer">
                            <li><a href="#"><i> </i></a></li>
                            <li><a href="#"><i> </i></a></li>
                            <li><a href="#"><i> </i></a></li>
                            <li><a href="#"><i> </i></a></li>
                            <li><a href="#"><i> </i></a></li>
                        </ul>
                        <div class="review">
                            <a href="#"> 1 customer review </a>

                        </div>
                        <div class="clearfix"> </div>
                    </div>

                    <h5 class="item_price">$ <?= $product->getPrice() ?></h5>
                    <p><?= $product->getDescription() ?></p>
                    <?= $this->form()->openTag($form); ?>
                    <div class="available">
                        <ul>
                            <li class="size-in">Start date
                                <?= $this->formElement($form->get('start')); ?></li>
                            <li>End date
                                <?= $this->formElement($form->get('end')); ?></li>
                            <li>Quantity
                                <?= $this->formElement($form->get('quantity')); ?></li>
                            <div class="clearfix"> </div>
                        </ul>
                        <script type="text/javascript">
                            $(function () {
                                $('#start').datetimepicker({
                                    locale: 'ru',
                                    stepping: '30'
                                });
                            });
                            $(function () {
                                $('#end').datetimepicker({
                                    locale: 'ru',
                                    stepping: '30'
                                });
                            });
                        </script>
                    </div>
                    <ul class="tag-men">
                        <li><span>TAG</span>
                            <span class="women1">: Women,</span></li>
                        <li><span>SKU</span>
                            <span class="women1">: CK09</span></li>
                    </ul>
                    <button class="add-cart item_add" type="submit">ADD TO CART</button>
                    <?= $this->form()->closeTag(); ?>
                </div>
            </div>
            <div class="clearfix"> </div>
            <!---->
            <div class="cd-tabs is-ended">
                <nav>
                    <ul class="cd-tabs-navigation">
                        <li><a data-content="fashion"  href="#0">Description </a></li>
                        <li><a data-content="cinema" href="#0" >Addtional Informatioan</a></li>
                        <li><a data-content="television" href="#0" class="selected ">Reviews (1)</a></li>

                    </ul>
                </nav>
                <ul class="cd-tabs-content">
                    <li data-content="fashion" >
                        <div class="facts">
                            <p > There are many variations of passages of Lorem Ipsum available, but the majority have suffered alteration in some form, by injected humour, or randomised words which don't look even slightly believable. If you are going to use a passage of Lorem Ipsum, you need to be sure there isn't anything embarrassing hidden in the middle of text. All the Lorem Ipsum generators on the Internet tend to repeat predefined chunks as necessary, making this the first true generator on the Internet. It uses a dictionary of over 200 Latin words, combined </p>
                            <ul>
                                <li>Research</li>
                                <li>Design and Development</li>
                                <li>Porting and Optimization</li>
                                <li>System integration</li>
                                <li>Verification, Validation and Testing</li>
                                <li>Maintenance and Support</li>
                            </ul>
                        </div>

                    </li>
                    <li data-content="cinema" >
                        <div class="facts1">

                            <div class="color"><p>Color</p>
                                <span >Blue, Black, Red</span>
                                <div class="clearfix"></div>
                            </div>
                            <div class="color">
                                <p>Size</p>
                                <span >S, M, L, XL</span>
                                <div class="clearfix"></div>
                            </div>

                        </div>

                    </li>
                    <li data-content="television" class="selected">
                        <div class="comments-top-top">
                            <div class="top-comment-left">
                                <img class="img-responsive" src="/img/co.png" alt="">
                            </div>
                            <div class="top-comment-right">
                                <h6><a href="#">Hendri</a> - September 3, 2014</h6>
                                <ul class="star-footer">
                                    <li><a href="#"><i> </i></a></li>
                                    <li><a href="#"><i> </i></a></li>
                                    <li><a href="#"><i> </i></a></li>
                                    <li><a href="#"><i> </i></a></li>
                                    <li><a href="#"><i> </i></a></li>
                                </ul>
                                <p>Wow nice!</p>
                            </div>
                            <div class="clearfix"> </div>
                            <a class="add-re" href="#">ADD REVIEW</a>
                        </div>

                    </li>
                    <div class="clearfix"></div>
                </ul>
            </div>
            <div class=" bottom-product">
                <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                    <div class="product-at ">
                        <a href="#"><img class="img-responsive" src="/img/pi3.jpg" alt="">
                            <div class="pro-grid">
                                <span class="buy-in">Buy Now</span>
                            </div>
                        </a>
                    </div>
                    <p class="tun">It is a long established fact that a reader</p>
                    <a href="#" class="item_add"><p class="number item_price"><i> </i>$500.00</p></a>
                </div>
                <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                    <div class="product-at ">
                        <a href="#"><img class="img-responsive" src="/img/pi1.jpg" alt="">
                            <div class="pro-grid">
                                <span class="buy-in">Buy Now</span>
                            </div>
                        </a>
                    </div>
                    <p class="tun">It is a long established fact that a reader</p>
                    <a href="#" class="item_add"><p class="number item_price"><i> </i>$500.00</p></a>					</div>
                <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                    <div class="product-at ">
                        <a href="#"><img class="img-responsive" src="/img/pi4.jpg" alt="">
                            <div class="pro-grid">
                                <span class="buy-in">Buy Now</span>
                            </div>
                        </a>
                    </div>
                    <p class="tun">It is a long established fact that a reader</p>
                    <a href="#" class="item_add"><p class="number item_price"><i> </i>$500.00</p></a>					</div>
                <div class="clearfix"> </div>
            </div>
        </div>

        <div class="clearfix"> </div>
    </div>
</div>
<!--//content-->