<table class="table table-striped">
<?php $form = $this->form ?>
    <tr>
        <th>Name</th>
        <th>Start date</th>
        <th>End date</th>
        <th>Quantity</th>
        <th>Price</th>
        <th>Actions</th>
    </tr>

    <?php foreach ($carts as $token=>$cart): ?>
        <tr>
            <td><?= $this->escapeHtml($cart->getProduct()); ?></td>
            <td><?= $this->escapeHtml($cart->getStart()); ?></td>
            <td><?= $this->escapeHtml($cart->getEnd()); ?></td>
            <td><?= $this->escapeHtml($cart->getQty()); ?></td>
            <td><?= $this->escapeHtml($cart->getPrice()); ?></td>
        </tr>

        <?= $this->form()->openTag($form); ?>
        <?php $form->get('hiddentoken')->setValue($token);?>
        <td>
            <?= $this->formElement($form->get('hiddentoken')); ?>
            <?= $this->formElement($form->get('update')); ?>
            <?= $this->formElement($form->get('delete')); ?>
        </td>
        <?= $this->form()->closeTag(); ?>
    <?php endforeach; ?>

</table>
<?= $this->escapeHtml($totalcost); ?>
<?= $this->form()->openTag($form); ?>
<?= $this->formElement($form->get('order')); ?>
<?= $this->form()->closeTag(); ?>