
<?php
$this->headTitle('Products');


$form->get('start')->setAttributes([
'class'=>'form-control',
'placeholder'=>'Starting date',
'required' => true,
])
->setLabelAttributes([
'class' => 'sr-only'
]);

$form->get('end')->setAttributes([
'class'=>'form-control',
'placeholder'=>'Ending date',
'required' => true,
])
->setLabelAttributes([
'class' => 'sr-only'
]);
?>

<?= $this->form()->openTag($form); ?>

<div class="container">
    <div class="row">
        <div class='col-sm-12'>
        <div class="form-group col-sm-12">
            <div class='input-group col-sm-6'>
                <?= $this->formLabel($form->get('category')); ?>
                <?= $this->formElement($form->get('category')); ?>
                <?= $this->formElementErrors($form->get('category')); ?>
            </div>
        </div>
        </div>
        <div class='col-sm-6'>

            <div class="form-group col-sm-6">
                <div class='input-group date' id='datetimepicker2'>
                    <?= $this->formLabel($form->get('start')); ?>
                    <?= $this->formElement($form->get('start')); ?>
                    <?= $this->formElementErrors($form->get('start')); ?>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <div class="form-group col-sm-6">
                <div class='input-group date' id='datetimepicker1'>
                    <?= $this->formLabel($form->get('end')); ?>
                    <?= $this->formElement($form->get('end')); ?>
                    <?= $this->formElementErrors($form->get('end')); ?>
                    <span class="input-group-addon">
                        <span class="glyphicon glyphicon-calendar"></span>
                    </span>
                </div>
            </div>
            <button class="btn btn-lg btn-primary btn-block" type="submit">Filter</button>
        </div>
        <script type="text/javascript">
            $(function () {
                $('#start').datetimepicker({
                    locale: 'ru',
                    stepping: '30'
                });
            });
            $(function () {
                $('#end').datetimepicker({
                    locale: 'ru',
                    stepping: '30'
                });
            });
        </script>
    </div>
</div>


<?= $this->form()->closeTag(); ?>









<?php if ($prodlist != null): ?>
<table class="table table-striped">

    <tr>
        <th>Name</th>
        <th>Description</th>
        <th>Price</th>
    </tr>

    <?php foreach($prodlist as $product):?>

        <tr>
            <td><?= $this->escapeHtml($product->getName()); ?></td>
            <td><?= $this->escapeHtml($product->getDescription()); ?></a>
            </td>
            <td><?= $this->escapeHtml($product->getPrice()); ?></td>
        </tr>
    <?php endforeach;?>

</table>

<?php endif;?>


