<?php

$form = $this->form;
$form->get('first_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter firstname here'
]);
$form->get('last_name')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Enter last name here'
]);
$form->get('gender')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Select gender here'
]);
$form->get('submit')->setAttributes(['class' => 'btn btn-primary']);
$form->get('submit')->setValue('Save');
$form->prepare();

?>

<h1>Edit user</h1>

<p>
    Enter new details
</p>

<div class="row">
    <div class="col-md-6">
        <?= $this->form()->openTag($form); ?>

        <div class="form-group">
            <?= $this->formLabel($form->get('first_name')); ?>
            <?= $this->formElement($form->get('first_name')); ?>
            <?= $this->formElementErrors($form->get('first_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('last_name')); ?>
            <?= $this->formElement($form->get('last_name')); ?>
            <?= $this->formElementErrors($form->get('last_name')); ?>
        </div>

        <div class="form-group">
            <?= $this->formLabel($form->get('gender')); ?>
            <?= $this->formElement($form->get('gender')); ?>
            <?= $this->formElementErrors($form->get('gender')); ?>
        </div>
        <?= $this->formElement($form->get('submit')); ?>

        <?= $this->form()->closeTag(); ?>
    </div>
</div>