<div class="banner">
    <div class="container">
        <script src="/js/responsiveslides.min.js"></script>
        <script>
            $(function () {
                $("#slider").responsiveSlides({
                    auto: true,
                    nav: true,
                    speed: 500,
                    namespace: "callbacks",
                    pager: true,
                });
            });
        </script>
        <div  id="top" class="callbacks_container">
            <ul class="rslides" id="slider">

            </ul>
        </div>

    </div>
</div>

<!--content-->
<div class="content">
    <div class="container">
        <div class="content-top">
            <h1>NEW RELEASED</h1>
            <div class="grid-in">
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>


                    <p><a href="single.html">Haibike Seet</a></p>
                </div>
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi1.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>
                    <p><a href="single.html">Pride Marvel</a></p>
                </div>
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi2.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>
                    <p><a href="single.html">Apollo Aspire</a></p>
                </div>
                <div class="clearfix"> </div>
            </div>
            <div class="grid-in">
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi3.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>
                    <p><a href="single.html">Cannondale Catalyst</a></p>
                </div>
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi4.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>
                    <p><a href="single.html">Apollo Transfer</a></p>
                </div>
                <div class="col-md-4 grid-top">
                    <a href="single.html" class="b-link-stripe b-animate-go  thickbox"><img class="img-responsive" src="/img/pi5.jpg" alt="">
                        <div class="b-wrapper">
                            <h3 class="b-animate b-from-left    b-delay03 ">
                                <span>Get Bicycle</span>
                            </h3>
                        </div>
                    </a>
                    <p><a href="single.html">Cyclone SLX</a></p>
                </div>
                <div class="clearfix"> </div>
            </div>
        </div>

    </div>