<link href="/css/bootstrap-datetimepicker.css" rel="stylesheet" type="text/css" media="all" />
<script src="/js/moment.js"> </script>
<script src="/js/bootstrap-datetimepicker.min.js"> </script>
<script src="/js/ru.js"> </script>


<?php
$this->headTitle('Products');


$form->get('start')->setAttributes([

    'id'=>'start_cat',
    'required' => true,
]);

$form->get('end')->setAttributes([
    'id'=>'end_cat',
    'required' => true,
]);
?>

<!--content-->
<!---->
<div class="product">
    <div class="container">
        <div class="col-md-3 product-price">

            <div class=" rsidebar span_1_of_left">
                <div class="of-left">
                    <h3 class="cate">Categories</h3>
                </div>
                <ul class="menu">
                    <?php $itemcount = null; foreach($categories as $category): $itemcount++; ?>
                    <li class="item<?= $itemcount ?>"><a href="<?= $this->url('shop/category',['id' => $itemcount]); ?>"><?= ucfirst($category->getName()) ?></a>
                        <ul class="cute">
                            <?php $subcount = null; foreach(($this->categoriesHelper()->findSubcategories($category)) as $subcategory): $subcount++;?>
                            <li class="subitem<?= $subcount ?>"><a href="<?= $this->url('shop/category/subcategory',['id'=>$category->getId(),'subid' => $subcategory->getId()]);?>"><?= ucfirst($subcategory->getName()) ?> </a></li>
                            <?php endforeach; ?>
                        </ul>
                    </li>
                    <?php endforeach; ?>
                </ul>
            </div>
            <!--initiate accordion-->
            <script type="text/javascript">
                $(function() {
                    var menu_ul = $('.menu > li > ul'),
                        menu_a  = $('.menu > li > a');
                    menu_ul.hide();
                    menu_a.click(function(e) {
                        e.preventDefault();
                        if(!$(this).hasClass('active')) {
                            menu_a.removeClass('active');
                            menu_ul.filter(':visible').slideUp('normal');
                            $(this).addClass('active').next().stop(true,true).slideDown('normal');
                        } else {
                            $(this).removeClass('active');
                            $(this).next().stop(true,true).slideUp('normal');
                        }
                    });

                });
            </script>
            <!---->

            <div class="sellers">
                <div class="of-left-in">
                    <h3 class="tag">Tags</h3>
                </div>
                <div class="tags">
                    <ul>
                        <li><a href="#">bicycles</a></li>
                        <li><a href="#">shop</a></li>
                        <li><a href="#">rent</a></li>
                        <li><a href="#">road</a></li>
                        <li><a href="#">bmx</a></li>
                        <li><a href="#">mountain</a></li>
                        <li><a href="#">men's</a></li>
                        <li><a href="#">women's</a></li>
                        <li><a href="#">rent</a></li>
                        <li><a href="#">store</a></li>
                        <li><a href="#">hybrid</a></li>
                        <li><a href="#">cruiser</a></li>

                        <div class="clearfix"> </div>
                    </ul>

                </div>

            </div>
            <!---->
            <div class="product-bottom">
                <div class="of-left-in">
                    <h3 class="best">Filters</h3>
                </div>
                <?= $this->form()->openTag($form); ?>
                <div class="available">
                    <ul>
                        <li class="size-in">Start date
                            <?= $this->formElement($form->get('start')); ?>
                            <?= $this->formElementErrors($form->get('start')); ?></li>
                        <li>End date
                            <?= $this->formElement($form->get('end')); ?>
                            <?= $this->formElementErrors($form->get('end')); ?></li>
                        <div class="clearfix"> </div>
                    </ul>
                    <button class="btn btn-default btn-block" type="submit">Filter</button>
                    <?= $this->form()->closeTag(); ?>
                    <script type="text/javascript">
                        $(function () {
                            $('#start_cat').datetimepicker({
                                locale: 'ru',
                                stepping: '30'
                            });
                        });
                        $(function () {
                            $('#end_cat').datetimepicker({
                                locale: 'ru',
                                stepping: '30'
                            });
                        });
                    </script>
                </div>

            </div>
            <div class=" per1">
                <a href="single.html" ><img class="img-responsive" src="/img/pro.jpg" alt="">
                    <div class="six1">
                        <h4>DISCOUNT</h4>
                    </div></a>
            </div>
        </div>
        <div class="col-md-9 product1">
            <?php $count = null; foreach($products as $product): $count++;?>
               <?php if($count==1 || $count==4 || $count==7): ?>
            <div class="bottom-product">
               <?php endif;?>
                <div class="col-md-4 bottom-cd simpleCart_shelfItem">
                    <div class="product-at ">
                        <a href="<?= $this->url('product',['action' => 'view', 'id' => $product->getId()]); ?>"><img class="img-responsive" src="/<?= $product->getLogo() ?>" alt="">
                            <div class="pro-grid">
                                <span class="buy-in">Buy Now</span>
                            </div>
                        </a>
                    </div>
                    <p class="tun"><?=$product->getName()?></p>
                    <a href="#" class="item_add"><p class="number item_price"><i> </i>$<?= $product->getPrice()?></p></a>
                </div>
                <?php if($count==3 || $count==6 || $count==9): ?>
                <div class="clearfix"> </div>
            </div>
                <?php endif; ?>
            <?php endforeach;?>
        </div>
        <div class="clearfix"> </div>
        <nav class="in">
            <?= $this->paginationControl($products,
                'Sliding',
                'shop/pagination/paginator',
                ['route' => 'shop/category', 'catid' => $catid]); ?>
        </nav>
    </div>

</div>

<!---->

<!--//content-->