<?php
$this->headTitle('Sign in');


$form->get('email')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Email address',
    'required' => true,
    'autofocus' => true
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);

$form->get('password')->setAttributes([
    'class'=>'form-control',
    'placeholder'=>'Password',
    'required' => true,
])
    ->setLabelAttributes([
        'class' => 'sr-only'
    ]);
?>




<div class="container">
    <div class="account">
        <h1>Account</h1>
        <div class="account-pass">
            <div class="col-md-8 account-top">
                <form method="post">
                    <?php if ($isLoginError): ?>
                        <div class="alert alert-warning" role="alert">
                            Incorrect login and/or password.
                            <a href="<?= $this->url('user') ?>">Forgot password?</a>
                        </div>
                    <?php endif; ?>
                    <div>
                        <?= $this->formLabel($form->get('email')); ?>
                        <?= $this->formElement($form->get('email')); ?>
                    </div>
                    <div>
                        <?= $this->formLabel($form->get('password')); ?>
                        <?= $this->formElement($form->get('password')); ?>
                    </div>
                    <a class="news-letter" style="display:block" href="#">
                        <label class="checkbox">
                            <?= $this->formElement($form->get('remember_me')); ?>
                            <i></i>Remember me</label>
                    </a>
                    <?= $this->formElement($form->get('redirect_url')); ?>
                    <?= $this->formElement($form->get('csrf')) ?>
                    <?= $this->formElement($form->get('submit')); ?>
                </form>
            </div>
            <div class="col-md-4 left-account ">
                <a href="single.html"><img class="img-responsive " src="/img/s1.jpg" alt=""></a>
                <div class="five">
                    <h2>25% </h2><span>discount</span>
                </div>
                <a href="register.html" class="create">Create an account</a>
                <div class="clearfix"> </div>
            </div>
            <div class="clearfix"> </div>
        </div>
    </div>

</div>