<!--content-->
<div class=" container">
    <div class=" register">
        <h1>Register</h1>
        <form>
            <div class="col-md-6 register-top-grid">
                <h3>Personal infomation</h3>
                <?= $this->form()->openTag($form); ?>
                <div>
                    <span>First Name</span>
                    <?= $this->formElement($form->get('first_name')); ?>
                    <?= $this->formElementErrors($form->get('first_name')); ?>
                </div>
                <div>
                    <span>Last Name</span>
                    <?= $this->formElement($form->get('last_name')); ?>
                    <?= $this->formElementErrors($form->get('last_name')); ?>
                </div>
                <div>
                    <span>Email Address</span>
                    <?= $this->formElement($form->get('email')); ?>
                    <?= $this->formElementErrors($form->get('email')); ?>
                </div>
                <a class="news-letter" href="#">
                    <label class="checkbox"><input type="checkbox" name="checkbox" checked=""><i> </i>Sign Up for Newsletter</label>
                </a>
            </div>
            <div class="col-md-6 register-bottom-grid">
                <h3>Login information</h3>
                <div>
                    <span>Password</span>
                    <?= $this->formElement($form->get('password')); ?>
                    <?= $this->formElementErrors($form->get('password')); ?>
                </div>
                <div>
                    <span>Confirm Password</span>
                    <?= $this->formElement($form->get('confirm_password')); ?>
                    <?= $this->formElementErrors($form->get('confirm_password')); ?>
                </div>
                <?= $this->formElement($form->get('submit')); ?>
                <?= $this->form()->closeTag(); ?>
            </div>
            <div class="clearfix"> </div>
        </form>
    </div>
</div>
<!--//content-->